//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin28.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JC_HC_USERS
    {
        public JC_HC_USERS()
        {
            this.JC_HC_USR_SND = new HashSet<JC_HC_USR_SND>();
        }
    
        public int ID { get; set; }
        public string LNAME { get; set; }
        public string FNAME { get; set; }
        public string AG_ID { get; set; }
        public string EMAIL { get; set; }
        public string OOF { get; set; }
        public string LOI_GRPS { get; set; }
        public Nullable<decimal> ESZ { get; set; }
        public string ZIP { get; set; }
        public string LEO { get; set; }
        public string ZIP2 { get; set; }
        public string ZIP3 { get; set; }
        public string RECD1 { get; set; }
        public string RECD2 { get; set; }
        public string RECD3 { get; set; }
        public string RECD4 { get; set; }
        public string RECD5 { get; set; }
        public string RECD6 { get; set; }
    
        public virtual ICollection<JC_HC_USR_SND> JC_HC_USR_SND { get; set; }
    }
}
