//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin28.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JC_HC_TYPES
    {
        public int ID { get; set; }
        public string TYCOD { get; set; }
        public string SUB_TYCOD { get; set; }
        public string AGENCY { get; set; }
        public string PRIORITY { get; set; }
        public Nullable<short> UN_CNT { get; set; }
        public string ALWYS_SND { get; set; }
        public string NEVR_SND { get; set; }
        public string NOT4PUB { get; set; }
    }
}
