//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin28.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JC_HC_USR_SND
    {
        public int ID { get; set; }
        public Nullable<int> USR_ID { get; set; }
        public Nullable<int> ESZ { get; set; }
        public Nullable<short> AGY_ID { get; set; }
        public string GRP_ID { get; set; }
        public Nullable<int> LOI_ID { get; set; }
    
        public virtual JC_HC_AGENCY JC_HC_AGENCY { get; set; }
        public virtual JC_HC_LOI JC_HC_LOI { get; set; }
        public virtual JC_HC_USERS JC_HC_USERS { get; set; }
    }
}
